### ISSUE TITLE
UnsolvedSymbolException

### ISSUE THREAD

**Issue by daiwenlong** [javaparser/javasymbolsolver-maven-sample#21]
code like this...

> 

    @ApiOperation(value = "注册账户信息", tags = "账户")
    public JsonResponseEntity<String> register(@RequestBody @Valid BankAccountDTO dto) {
        UserBasic user = UserUtil.getUserInfo();
        MobileInfo mobileInfo = new MobileInfo(dto.getContactPhone(), dto.getVerificationCode());
        String status = accountServiceApplication.register(null, user.getUid(), user.getUsername());
        return JsonResponseEntity.ok(status);
    }

`

> 
        CombinedTypeSolver combinedTypeSolver = new CombinedTypeSolver();
        TypeSolver reflectionTypeSolver = new ReflectionTypeSolver(false);
        JavaParserTypeSolver javaParserTypeSolver = new JavaParserTypeSolver(new File("D:\\ideawork\\src\\main\\java"));
        combinedTypeSolver.add(reflectionTypeSolver);
        combinedTypeSolver.add(javaParserTypeSolver);

        JavaSymbolSolver symbolSolver = new JavaSymbolSolver(combinedTypeSolver);
        StaticJavaParser.getConfiguration().setSymbolResolver(symbolSolver);
`

Exception:UnsolvedSymbolException{context='null', name='We are unable to find the method declaration corresponding to dto.getContactPhone()', cause='null'}

How to deal with it?

**Comment by jlerbsc** [comment]
Hi @daiwenlong could you confirm that BankAccountDTO is accessible from the source directory (D:\ideawork\src\main\java)?
